---
title: "Accessibility"
author: "Megsie Siple"
date: "7/21/2020"
output: 
  html_document:
    theme: lumen
    toc: true
    toc_float: true
    fig_width: 11
    fig_height: 8
---


# Introduction

Online tools should be accessible to the broadest possible audience. I have been thinking about ways to measure how usable software is, and how easily it can be used and interpreted by a broad user group. As far as I know, there are not a lot of packages or tools that enhance accessibility for Shiny apps, although as discussed below there are some features that are built into the defaults, that improve usability. 

# Summary

The primary shortcomings based on my non-expert assessment are that the informative pop-ups do not fit the guidelines, and the visual experience of using the app (colors, contrast) are not currently under user control. Both of these changes will require some complex HTML or CSS, but should be possible. Otherwise the app in its current state complies with most of the WCAG guidelines for web content. After the initial comment period, the status of some of these may change. 

# WCAG guidelines

The Web Accessibility Initiative publishes Web Content Accessibility Guidelines (WCAG) and the requirements and techniques for meeting each of those guidelines. I went through those guidelines and checked which ones the current version of this Shiny app complies with, and where it could be improved/how feasible it would be to improve. 

[WCAG 2]((https://www.w3.org/WAI/standards-guidelines/wcag/)) gives a technical standard for developers to make content as accessible as possible for a wide audience. 

WCAG describe three primary principles:

- Perceivable
- Operable
- Understandable

Each of these principles has some sub-categories, so I will organize this sheet based on their principles and the subcategories. All of the information included here is from WCAG unless otherwise stated. I am assessing the compliance of the [NMFS Acoustic Deterrent Web Tool](https://msiple.shinyapps.io/acousticdeterrents/) with all of these criteria.

# Perceivable

## Text alternatives

All non-text content should have a text alternative that "serves the equivalent purpose." In the case of this tool, the only images that are not completely text are the red and green highlights in the table containing the isopleth distances (the table is shown at the top of each tab). These highlights show the same information as a column to the right, which has checkmarks and "yes"/"no" for compliance that contain the same information as green and red coloring.

## Time-based media

Time-based media are things like video and audio recordings. There are none of those in this tools, so this guideline does not apply to the acoustic deterrrent tool.

## Adaptable

This guideline means content can be presented in different ways (e.g., a simpler layout) without losing information or structure. In this tool, all the tabs can be used out of order, and information is presented from top to bottom in each tab. The certificate buttons are at the bottom of each page where users enter calculations, so they don't need to know to go elsewhere in the app. Orientation is all in the same direction. The only icons present in the the tool are also shown with text. Input fields are clear and can be determined either from reading the box title or from the tooltips, which appear when the user hovers over the box.

## Distinguishable

This category covers how users see and hear content, including separating foreground from background. Color is used minimally and users do not need to be able to distinguish between colors to use the tool successfully. Contrast is high (everything is currently black text on white background, including the tables with results that users will be looking at, and the resulting certificate). Text can be resized up to 200% without losing the ability to read and interpret the pages. There are pictures of text in the "Help" tab, but these pictures are provided only as assistance for people in reading their device specs, the proper use of this tool does not rely entirely on people being able to read the text in the images.

The visual presentation part of this tool is one of two places where it could be improved for this principle: Currently, the user cannot select foreground and background colors; they are fixed. Ideally, this tool would have a switch or other settings fixed on each page that would allow the user to select foreground and background color. This feature may be difficult to add but should be possible using raw HTML.

This criterion also includes guidelines for information presented on a pointing hover: when users hover over data entry locations, tooltips appear with descriptions and/or additional instructions. These should be **dismissible**, **hoverable**, and **persistent**. The Shiny tooltip default is that hovering over the text triggers the tooltip, and only moving away from it dismisses the information. It is also not **persisent** because moving the mouse over the text in the tooltip makes the tip itself disappear. Thus, the tooltips do not comply with the WCAG criteria, but they do appear outside the field where the user is typing, so are unlikely to be obstructing their view (i.e., the **dismissible** part may not be as much of an issue as it could be.

# Operable

## Keyboard Accessible

Shiny apps are keyboard accessible by default; tabs and 'Enter' can be used through to navigate among and within tabs. Keyboard focus can be moved away from any of the components at any time (i.e., there are no "keyboard traps"). There are no character key shortcuts.

## Enough Time

There is nothing time-sensitive in this app; some features auto-update instantaneously, and everything else is dictated by the user by clicking one of the buttons (e.g., the generation of the certificate).

A possible sticking point for this tool (and any other Shiny app) is that it will time out on the server if the user is "inactive" for a long amount of time. This can be fixed by the server administrator so should not be a problem once the app is hosted on the NOAA rsconnect server.


## Seizures and Physical Reactions

There are no flashes or animations in this app, so it is compliant with this criterion by default. 

## Navigable

User location is highlighted and/or outlined on every tab (this is Shiny's default). There are headings and labels for all features, and every tab is accessible from every other tab. Link purposes are clearly stated. 

## Input Modalities

All input can be changed using standard keystroke commands (e.g., a number can be "undone" if the user types Ctl-Z while in the numeric field for any one of the inputs). There are no drag-and-drop functions in the tool. The cursor is the same as whatever users are utilizing in their browser. 

# Understandable

## Readable

Shiny apps can be translated using google translate, so the language I think can be "programmatically determined." All regulatory jargon is defined (although the public comment period will probably indicate areas where it can be clarified). All acronyms are defined. I am not sure what the reading level is, but the language is clear and sentences are short. The pages should be readable with a screen reader though I have not tested it yet.

## Predictable

The only change in features that is not obviously triggered by user input is the disappearance of the "Generate Certificate" button when the device is not compliant. It is indirectly influenced by the parameters that the user puts in. There is consistent navigation, i.e., the navigation mechanism is replicated on every page ont he site. The instructions indicate to the user that the outputs will change when they adjust the inputs.

## Input Assistance

Error identification might be added later after testing; currently the outputs change in a way that makes mistakes fairly obvious (and the functionality of the tool still works), but we may add "friendly" error messages if values the user enters are outside a realistic range. No data are stored by the app, so there are no legal issues with data management. The user is unable to generate a certificate for their device if the device is not in compliance.

# Robust
## Compatible

All app attributes are unique (they have to be in order for the app to function). There are status messages that change when the device is or isn't in compliance with NMFS guidelines.