---
title: "NMFS Acoustic Deterrents Web Tool"
subtitle: "Certificate of approval"
output: 
  html_document:
    self_contained: yes
    highlight: pygments
params:
  lowest_frequency: NA
  highest_frequency: NA
  max_loudness: NA
  max_ping_dur: NA
  min_silent: NA
  duty_cycle_direct: NA
  name: NA
  devicename: NA
  characteristics: NA
  isopleth.table: NA
  species.to.deter: NA
  ESA: NA
---

```{css, echo=FALSE}
.watermark {
  opacity: 0.1;
  position: fixed;
  top: 20%;
  left: 50%;
  font-size: 500%;
  color: #00407d;
}
```


```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri(here::here("NOAA_logo.svg")),
               alt = 'logo',
               style = 'position:absolute; top:0; right:0; padding:10px; width: 100px')
```


<div class="watermark" align="center">CERTIFICATE NOT VALID UNTIL GUIDELINES FINALIZED</div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#options(knitr.table.format = "html") 
library(tidyverse)
library(kableExtra)

lowest_frequency = params$lowest_frequency
highest_frequency = params$highest_frequency
max_loudness = params$max_loudness # also called "source level"
max_ping_dur = params$max_ping_dur
min_silent = params$min_silent
duty_cycle = params$duty_cycle_direct
name = params$name
devicename = params$devicename
characteristics = params$characteristics
expiration = Sys.Date() + 365
isopleth.table = params$isopleth.table
species.to.deter = params$species.to.deter
ESA = params$ESA
```

`r ESA`

`r name` is approved to use the deterrent noted below according to the following specifications until `r expiration`.



Deterrent name: `r devicename`

Deterrent details: `r characteristics`

Expiration date: `r expiration`

Marine mammal species being deterred: `r species.to.deter`


## Specifications entered:
```{r echo = FALSE}

if(!is.na(duty_cycle)){
  x <- data.frame(Specification = c("Lowest deterrent frequency (kHz)",
                                  "Highest deterrent frequency (kHz)",
                                  "Source level (RMS SPL)",
                                  "Duty cycle (%)"),
                Value = c(lowest_frequency,highest_frequency,max_loudness,duty_cycle))
}else{
x <- data.frame(Specification = c("Lowest deterrent frequency (kHz)",
                                  "Highest deterrent frequency (kHz)",
                                  "Source level (RMS SPL)",
                                  "Ping/pulse duration (seconds)",
                                  "Silent period between pings/pulses (seconds)"),
                Value = c(lowest_frequency,highest_frequency,max_loudness,max_ping_dur,min_silent))
}
x %>%
  kable(escape=FALSE) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

<!-- ## NMFS evaluation criteria -->
<!-- ```{r echo = FALSE} -->
<!-- y <- params$isopleth.table -->
<!-- y  %>% -->
<!--   select(-isopleth) %>% -->
<!--   kable(escape=FALSE) %>% -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "condensed")) -->
<!-- ``` -->